services:
  postgres:
    build: .                 # Dockerfile in same folder
    container_name: postgresCont
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
